spring:
  profiles:
    active: @spring.profiles.active@
---
spring:
  profiles: default
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.16.16.235:5432/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: postgres
    password: pgsql11@aiidc.com
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
---
spring:
  profiles: dm
  datasource:
    url: jdbc:dm://172.16.16.235:8765
    username: TESTUSER
    password: 123456789
    driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.DmDialect
 #     hibernate:
 #       ddl-auto: create
---